version: '3.7'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      grafana-network1:
        aliases:
          - grafana
    restart: unless-stopped


networks:
  grafana-network1:
    external: true
