version: '3'
services:
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - grafana-network1
    ports:
      - "8000:8000"  

networks:
  grafana-network1:
    external: true
