version: '3.7'
services:
  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    volumes:
    - ./tempo.yaml:/etc/tempo/tempo.yaml
    ports:
      - "3200:3200"
    networks:
      grafana-network1:
        aliases:
          - tempo
    command: ["-config.file=/etc/tempo/tempo.yaml"]
    restart: unless-stopped
networks:
  grafana-network1:
    external: true
